// <auto-generated />
using System;
using AppAvisos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppAvisos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512143316_Protocolo")]
    partial class Protocolo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppAvisos.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId", "Slug")
                        .IsUnique();

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Aviso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnexoNome")
                        .HasColumnType("text");

                    b.Property<long?>("AnexoTamanho")
                        .HasColumnType("bigint");

                    b.Property<string>("AnexoUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArquivadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BlocoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Escopo")
                        .HasColumnType("integer");

                    b.Property<bool>("Fixado")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MoradorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublicarEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Template")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Urgente")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ValidoAte")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.HasIndex("CondominioId", "CriadoEm");

                    b.ToTable("Avisos");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.AvisoRecibo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvisoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CienteEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmailAbertoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAbertoIp")
                        .HasColumnType("text");

                    b.Property<string>("EmailAbertoUserAgent")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailEnviadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmailProximaTentativaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmailTentativas")
                        .HasColumnType("integer");

                    b.Property<Guid>("MoradorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PushEnviadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PushProximaTentativaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PushTentativas")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RespondidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resposta")
                        .HasColumnType("text");

                    b.Property<string>("VisualizadoCidade")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VisualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisualizadoEstado")
                        .HasColumnType("text");

                    b.Property<string>("VisualizadoIp")
                        .HasColumnType("text");

                    b.Property<string>("VisualizadoPais")
                        .HasColumnType("text");

                    b.Property<string>("VisualizadoUserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MoradorId");

                    b.HasIndex("AvisoId", "MoradorId")
                        .IsUnique();

                    b.ToTable("AvisoRecibos");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Bloco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId", "Nome")
                        .IsUnique();

                    b.ToTable("Blocos");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.CategoriaAviso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId", "Nome")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Condominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BloqueadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("CorPrimaria")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoCurta")
                        .HasColumnType("text");

                    b.Property<string>("EmailContato")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<bool>("IdentificacaoObrigatoria")
                        .HasColumnType("boolean");

                    b.Property<bool>("Inadimplente")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("MotivoBloqueio")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ObservacoesMaster")
                        .HasColumnType("text");

                    b.Property<string>("Site")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TelefoneContato")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoPagamentoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Condominios");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Morador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apartamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("AprovadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("BlocoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailInvalido")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TokenReset")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenResetExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlocoId");

                    b.HasIndex("CondominioId", "Email")
                        .IsUnique();

                    b.ToTable("Moradores");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MoradorId")
                        .HasColumnType("uuid");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoUso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("MoradorId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Reporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apartamento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bloco")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FotosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("RespondidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RespondidoPor")
                        .HasColumnType("text");

                    b.Property<string>("Resposta")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("TokenPublico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Protocolo")
                        .IsUnique()
                        .HasFilter("\"Protocolo\" <> ''");

                    b.HasIndex("TokenPublico")
                        .IsUnique();

                    b.HasIndex("CondominioId", "CriadoEm");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.TimelineMensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("AutorTipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("AvisoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MoradorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MoradorId");

                    b.HasIndex("AvisoId", "MoradorId", "CriadoEm");

                    b.ToTable("Timeline");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CondominioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenReset")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenResetExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Area", b =>
                {
                    b.HasOne("AppAvisos.Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Aviso", b =>
                {
                    b.HasOne("AppAvisos.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("AppAvisos.Domain.Entities.CategoriaAviso", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("AppAvisos.Domain.Entities.Condominio", "Condominio")
                        .WithMany("Avisos")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Categoria");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.AvisoRecibo", b =>
                {
                    b.HasOne("AppAvisos.Domain.Entities.Aviso", "Aviso")
                        .WithMany("Recibos")
                        .HasForeignKey("AvisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppAvisos.Domain.Entities.Morador", "Morador")
                        .WithMany()
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aviso");

                    b.Navigation("Morador");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Bloco", b =>
                {
                    b.HasOne("AppAvisos.Domain.Entities.Condominio", "Condominio")
                        .WithMany("Blocos")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.CategoriaAviso", b =>
                {
                    b.HasOne("AppAvisos.Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Morador", b =>
                {
                    b.HasOne("AppAvisos.Domain.Entities.Bloco", "Bloco")
                        .WithMany()
                        .HasForeignKey("BlocoId");

                    b.HasOne("AppAvisos.Domain.Entities.Condominio", "Condominio")
                        .WithMany("Moradores")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bloco");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("AppAvisos.Domain.Entities.Morador", "Morador")
                        .WithMany()
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Morador");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("AppAvisos.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AppAvisos.Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.TimelineMensagem", b =>
                {
                    b.HasOne("AppAvisos.Domain.Entities.Aviso", "Aviso")
                        .WithMany()
                        .HasForeignKey("AvisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppAvisos.Domain.Entities.Morador", "Morador")
                        .WithMany()
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aviso");

                    b.Navigation("Morador");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("AppAvisos.Domain.Entities.Condominio", "Condominio")
                        .WithMany()
                        .HasForeignKey("CondominioId");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Aviso", b =>
                {
                    b.Navigation("Recibos");
                });

            modelBuilder.Entity("AppAvisos.Domain.Entities.Condominio", b =>
                {
                    b.Navigation("Avisos");

                    b.Navigation("Blocos");

                    b.Navigation("Moradores");
                });
#pragma warning restore 612, 618
        }
    }
}
